/** Официальные домены дизайнеров. Ключ — нормализованное имя (без пробелов/знаков, lowercase). */
const BRAND_DOMAINS: Record<string, string> = {
  gucci: "gucci.com",
  prada: "prada.com",
  versace: "versace.com",
  dolcegabbana: "dolcegabbana.com",
  dg: "dolcegabbana.com",
  balenciaga: "balenciaga.com",
  saintlaurent: "ysl.com",
  yslsaintlaurent: "ysl.com",
  ysl: "ysl.com",
  valentino: "valentino.com",
  fendi: "fendi.com",
  armani: "armani.com",
  emporioarmani: "armani.com",
  giorgioarmani: "armani.com",
  burberry: "burberry.com",
  moschino: "moschino.com",
  offwhite: "off---white.com",
  stoneisland: "stoneisland.com",
  moncler: "moncler.com",
  hugoboss: "hugoboss.com",
  boss: "hugoboss.com",
  ralphlauren: "ralphlauren.com",
  poloralphlauren: "ralphlauren.com",
  tommyhilfiger: "tommy.com",
  calvinklein: "calvinklein.com",
  michaelkors: "michaelkors.com",
  karllagerfeld: "karl.com",
  dsquared2: "dsquared2.com",
  dsquared: "dsquared2.com",
  philippplein: "plein.com",
  balmain: "balmain.com",
  givenchy: "givenchy.com",
  bottegaveneta: "bottegaveneta.com",
  jimmychoo: "jimmychoo.com",
  ferragamo: "ferragamo.com",
  salvatoreferragamo: "ferragamo.com",
  kenzo: "kenzo.com",
  diesel: "diesel.com",
  lacoste: "lacoste.com",
  guess: "guess.com",
  liujo: "liujo.com",
  pinko: "pinko.com",
  furla: "furla.com",
  coccinelle: "coccinelle.com",
  trussardi: "trussardi.com",
  cavalli: "robertocavalli.com",
  robertocavalli: "robertocavalli.com",
  elisabettafranchi: "elisabettafranchi.com",
  patriziapepe: "patriziapepe.com",
  twinset: "twinset.com",
  iceberg: "iceberg.com",
  billionaire: "billionaire.com",
  zegna: "zegna.com",
  ermenegildozegna: "zegna.com",
  canadagoose: "canadagoose.com",
  parajumpers: "parajumpers.it",
  woolrich: "woolrich.com",
  maxmara: "maxmara.com",
  celine: "celine.com",
  loewe: "loewe.com",
  chloe: "chloe.com",
  alexandermcqueen: "alexandermcqueen.com",
  mcqueen: "alexandermcqueen.com",
  palmangels: "palmangels.com",
  amiri: "amiri.com",
  ami: "amiparis.com",
  amiparis: "amiparis.com",
  jacquemus: "jacquemus.com",
  marni: "marni.com",
  etro: "etro.com",
  missoni: "missoni.com",
  emiliopucci: "pucci.com",
  pucci: "pucci.com",
  lanvin: "lanvin.com",
  courreges: "courreges.com",
  goldengoose: "goldengoose.com",
  premiata: "premiata.it",
  santoni: "santonishoes.com",
  churchs: "church-footwear.com",
  tods: "tods.com",
  hoganshoes: "hogan.com",
  hogan: "hogan.com",
};

export function normalizeBrand(designer: string): string {
  return designer.toLowerCase().replace(/[^a-z0-9]/g, "");
}

export function officialDomain(designer: string): string | undefined {
  return BRAND_DOMAINS[normalizeBrand(designer)];
}
